#
# Issue & PR templates
#
# `/issues/new/choose`  
# `/issues/new?template=bug-report.yml`  
#
# > About YAML syntax for issue forms | https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# > About GitHub's form schema        | https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#about-githubs-form-schema
#

name: バグレポート
description: 不具合など起きている問題を報告する
title: "[不具合]: "
labels: ["bug"]
body:

  - type: textarea
    id: current-behavior
    attributes:
      label: 不具合の内容
      description: |
        どんな問題が起きているか説明してください。
        **OhTenki Japan** 以外のスキンを閉じた状態でも問題が起きますか?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > この入力欄をクリックして選択し、ファイルをドラッグすることで画像を添付できます。

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: 不具合の再現方法を記入してください。(できるだけ簡潔かつ正確に)
      description:  |
        ""

  - type: textarea
    id: environment
    attributes:
      label: 動作環境
      description:  |
        1. Rainmeterアイコンを右クリック > 詳細 > バージョン
        1. `クリップボードにコピー` ボタンをクリックし、 入力欄に貼り付けてください。
      placeholder: |
        <例>
        Rainmeter 4.5.23.3836 (64-bit)
        Language: Japanese (1041)
        Build time: 2025-04-12 17:25:59
        Windows 11 Pro 24H2 (build 26100.6584) 64-bit - Japanese (1041)
    validations:
      required: true
