# > About YAML syntax for issue forms | https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

name: Bug Report
description: Create a new issue as a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: |
        Describe how the issue manifests. What went wrong?

        > [!Tip]  
        > You can attach images by clicking this area to highlight it and then dragging files in.  
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce it (as minimally and precisely as possible)
      description: |
                    - Unload all skins except **OhTenki Japan** skin

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description:  |
        1. Right-click the Rainmeter icon > About > Version
        1. Click the `Copy to clipboard` button, then paste it into the textarea.
        
      placeholder: |
        Rainmeter 4.5.23.3836 (64-bit)
        Language: English (1033)
        Build time: 2025-04-12 17:25:59
        Windows 11 Pro 24H2 (build 26100.6584) 64-bit - English (1033)
    validations:
      required: true
