# > About YAML syntax for issue forms | https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: ["nek7u/OhTenki-Japan"]
assignees:
  - nek7u
body:
  - type: textarea
    id: current-behavior
    attributes:
      label: "Current behavior"
      description: "Describe how the issue manifests. What went wrong?"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected behavior"
      description: "Describe what the desired behavior should be. What did you expect?"

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: "How to reproduce it (as minimally and precisely as possible) 🔬"
      description: |
                    Please provide a **MINIMAL REPRO PROJECT** and the **STEPS TO REPRODUCE**

                    To create a minimal reproduction project:
                    - Unload all skins except **OhTenki Japan** skin

  - type: textarea
    id: workaround
    attributes:
      label: "Workaround️"
      description: "Please provide steps to workaround this problem if possible. Got a hack? Share it! 💡"

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
