blank_issues_enabled: true
contact_links:
  - name: FAQ - トラブルシューティング
    url: https://github.com/nek7u/OhTenki-Japan/wiki/FAQ#%E3%83%88%E3%83%A9%E3%83%96%E3%83%AB%E3%82%B7%E3%83%A5%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0
    about: よくある質問
  - name: Rainmeter Documentation
    url: https://docs.rainmeter.net
    about: マニュアル
